version: '3.3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: videojuegos
    #restart: always
    depends_on:
      - db-videojuegos
    ports:
      - 8000:8000
      # - 80:80
    volumes:
      - ./app:/app
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}

  db-videojuegos:
    image: mariadb
    container_name: videojuegos-db 
    #restart: always
    environment:
      MYSQL_DATABASE: videojuegos
      MYSQL_USER: videojuegos_user
      MYSQL_PASSWORD: uriel12.
      MYSQL_ROOT_PASSWORD: admin1234
    volumes:
      - db-videojuegos:/var/lib/mysql
    ports:
      - 3320:3306

volumes:
  db-videojuegos:
  
